Abkürzungen
NAVO
FITConnect

* Glossar
OFA - Online Fachverfahren
OFA-Labore - Fachverfahrenhersteller
HzL - Hilfe zum Lebensunterhalt
HzL - Labor ??
XÖV - Standard Standard Schnittsteller Öffentliche Verwaltung
XÖV - Fachstandard
XSozial-Basis
EFA - Einer für alle
FIM - Föderales Informationsmanagement (wie ist die Leistung beschrieben, wie sieht der Prozess aus, und welche Datenfelder werden benötigt) 
OD - ??


Das OZG Datenschema mit der Version 1. EGH (Eingliederungshilfe ist nicht final) 2.  Landesblindengeld. 



* meeting von heute
Anforderungen über ein Muster Template ( Anforderung) in den Prozess eingesteuert.
Link zum SharePoint anfordern ...

* LS
** Beschreibung: DVfR, Deutsche Vereinigung für Rehabilitätion
** Ansprechpartner sind Herr Engel und Herr Kinas.

Offener Punkt mit LS: Werden schon online Bescheide versandt ?

* Materna
** Was machen die
*** https://www.materna.de/EN/Home/home_node.html


* BEC
** Entwickelt Softwarelösungen für die öffentlichen Verwaltungen
** https://www.bec.de/


* FjD
** Hersteller der NAVO Plattform
** https://www.fjd.de/

*** Beweiswerterhaltung

*** Reinhard Weber PO
*** Sabine Lieckfeldt ??
*** Wallat
*** T
*** Basal Nasir


**** Widerspruchsverfahren:
Wie muss die Vorlage aussehen
Wir bekommen das Template
Vorstellen von der Strecke





* Fachverfahrenhersteller:
** Prosoz
*** Zulieferer für Software
*** https://www.prosoz.de/

**** 26.04.2023 Termin mit Herrn Beier, Frau Wallat 
Kosten können laut Frau Wallat nicht direkt aber auch nicht indirekt über die Kommunen abgedeckt werden. Dies liegt einzig und allein in der Verantwortung des Fachverfahrenherstellers.
Es ist Beihilferechtswidrig, wenn die Kommunen jetzt die Prositz bezahlen.
Herr Beier war da etwas offener und schlug eine Förderung der Kommunen an, was eigentliche eine indirekte Förderung der Fachverfahrenhersteller gleich kommt.
Einigkeit darüber, dass Standards nicht übereinstimmen, der aktuelle Standard ist veraltet.


** Lämmerzahl
Zulieferer für Software
https://www.laemmerzahl.de/

*** Jour Fix vom 04.05.2023
// Unzufrieden mit der aktuellen Kommunikation
// Das EGH Schema wurde zurückgezogen - ohne Begründung - ohne eindeutige Kommunikation - ohne belastbaren Zeitplan
// Informationen von Jess, Adrian, Frau Wallat
// Das HzP Schema ist noch nicht freigegeben, da Lämmerzahl intern Ressourcen zu den Entwicklungen allokieren muss, warten die hier.
// Informationen von Jess
// Über Prosoz hatte Lämmerzahl erfahren, das XSozial basis  zurückgezogen werden soll, da Lämmerzahl in der Entwicklung schon fortgeschritten ist. Wäre dies sehr ungünstig.
// Basal: XSozial basis bieten wir gar nicht an, Absicherung von Jess




